\chapter{The Joint Optimization of Fidelity and Commensurability  solution \\ to Seeded Graph Matching}
\label{sec:sgm-jofc}
\chaptermark{Seeded Graph Matching and JOFC}

\section{Overview}
We first explain the relevance of the JOFC approach to the graph matching problem. The task of finding vertex correspondences is similar to  detecting matched pairs\ref{chap:match_detection} in that both of the tasks require the quantification of a distance between vertex pairs in different graphs. A joint commensurate representation of the vertices of the two graphs  can be used to compute these distances between vertex pairs.
